name: "create-release-page"
description: "Create release page"
author: "Marius Mihalcea"
branding:
  color: 'yellow'

inputs:
  token:
    description: "The github token with permisions."
    required: true
  build_version:
    description: "The version of the build."
    required: true
  change_log_file:
    description: "The file where the change log are writed."
    required: false
  name: 
    description: "The name of the release."
    required: false
  find_pattern:
    description: "The pattern to find the version in the change log file."
    required: false
    default: "v{version}"
  draft:
    description: "If the release is a draft or not."
    required: false
    default: "false"
runs:
  using: node20
  main: dist/index.js
