name: Test Action
on:
    workflow_dispatch:

permissions:
    contents: write
    workflows: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run create-release-page action
              uses: ./
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                build_version: "1.0.0"
                change_log_file: "CHANGELOG.md"
                name: "Release 1.0.0"


                