name: Test Action
on:
    workflow_dispatch:
      inputs:
          tag_name:
              description: 'Tag name for the release'
              required: true
              default: 'v1.0.0'
          change_log_file:
              description: 'Path to the changelog file'
              required: true
              default: 'CHANGELOG.md'
          name:
              description: 'Name of the release'
              required: true
              default: 'Release 1.0.0'

permissions:
    contents: write
    actions: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run create-release-page action
              uses: ./
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                tag_name: ${{ inputs.tag_name }}
                change_log_file: ${{ inputs.change_log_file }}
                name: ${{ inputs.name }}


                